<a href="https://colab.research.google.com/github/salim928/GEN-AI/blob/adamstemp/Text_Representation_Word_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.DataFrame({"text":["people with salim",
                          "salim watch salim",
                          "people write comment",
                          "salim write comment"], "output":[1,1,0,0]})
df

text  output
0     people with salim       1
1     salim watch salim       1
2  people write comment       0
3   salim write comment       0

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [7]:
bow = cv.fit_transform(df["text"])

In [8]:
#Vocabulary
print(cv.vocabulary_)

{'people': 1, 'with': 4, 'salim': 2, 'watch': 3, 'write': 5, 'comment': 0}


In [9]:
bow.toarray()

array([[0, 1, 1, 0, 1, 0],
       [0, 0, 2, 1, 0, 0],
       [1, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 1]])

In [10]:
X = bow.toarray()
y = df["output"]

# N-grams

In [11]:
df = pd.DataFrame({"text":["people with salim",
                          "salim watch salim",
                          "people write comment",
                          "salim write comment"], "output":[1,1,0,0]})
df

text  output
0     people with salim       1
1     salim watch salim       1
2  people write comment       0
3   salim write comment       0

In [12]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [13]:
bow = cv.fit_transform(df["text"])

In [14]:
#vocabulary
print(cv.vocabulary_)

{'people with': 0, 'with salim': 5, 'salim watch': 2, 'watch salim': 4, 'people write': 1, 'write comment': 6, 'salim write': 3}


In [15]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 0 1 0]]
[[0 0 1 0 1 0 0]]


In [16]:
df = pd.DataFrame({"text":["people with salim",
                          "salim watch salim",
                          "people write comment",
                          "salim write comment"], "output":[1,1,0,0]})
df

text  output
0     people with salim       1
1     salim watch salim       1
2  people write comment       0
3   salim write comment       0

In [17]:
# Tri grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [18]:
bow = cv.fit_transform(df["text"])

In [19]:
#vocabulary
print(cv.vocabulary_)

{'people with salim': 0, 'salim watch salim': 2, 'people write comment': 1, 'salim write comment': 3}


# TF-IDF(Term Frequency-Inverse document frequency)

In [20]:
df = pd.DataFrame({"text":["people with salim",
                          "salim watch salim",
                          "people write comment",
                          "salim write comment"], "output":[1,1,0,0]})
df

text  output
0     people with salim       1
1     salim watch salim       1
2  people write comment       0
3   salim write comment       0

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()

In [22]:
arr = tf.fit_transform(df['text']).toarray()

In [23]:
arr

array([[0.        , 0.55349232, 0.44809973, 0.        , 0.70203482,
        0.        ],
       [0.        , 0.        , 0.78722298, 0.61666846, 0.        ,
        0.        ],
       [0.57735027, 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027],
       [0.61366674, 0.        , 0.49681612, 0.        , 0.        ,
        0.61366674]])

In [24]:
print(tf.idf_)

[1.51082562 1.51082562 1.22314355 1.91629073 1.91629073 1.51082562]


# Word2Vec

In [25]:
import numpy as np
import pandas as pd
import gensim
import os

In [26]:
!pip install --upgrade gensim --user

In [27]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [28]:
story = []
for filename in os.listdir("DATA"):
  if filename == '.ipynb_checkpoints':
    pass
  f = open(os.path.join("DATA",filename))
  corpus = f.read()
  raw_sent = sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [29]:
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [30]:
story[0]

['game',
 'of',
 'thrones',
 'book',
 'one',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george',
 'martin',
 'prologue',
 'we',
 'should',
 'start',
 'back',
 'gared',
 'urged',
 'as',
 'the',
 'woods',
 'began',
 'to',
 'grow',
 'dark',
 'around',
 'them']

In [31]:
len(story)

27244

In [32]:
# intialize the gensim model to work on the WORD2VEC

model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [33]:
# Convert to the vector representation
model.build_vocab(story)

In [34]:
# train the data on the model
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(1059143, 1423500)

In [35]:
# most similar word
model.wv.most_similar("daenerys")

[('halder', 0.9961947202682495),
 ('rush', 0.9961229562759399),
 ('flowers', 0.9960708618164062),
 ('giant', 0.9956431984901428),
 ('dull', 0.9956006407737732),
 ('mycah', 0.9954244494438171),
 ('riding', 0.9953438639640808),
 ('fat', 0.9950932264328003),
 ('tyrell', 0.9949395656585693),
 ('septon', 0.9948530793190002)]

In [36]:
# similarity amongst the 2 names
model.wv.similarity("arya","sansa")

0.9826384

In [37]:
# #
model.wv.similarity("arya","daenerys")

0.80401266

In [38]:
model.wv['deep'].shape

(100,)

In [39]:
# All the vectors
vec = model.wv.get_normed_vectors()

In [40]:
vec

array([[-0.08108761,  0.04061922,  0.03442835, ..., -0.17641108,
        -0.01792656,  0.09835553],
       [-0.10714711,  0.07618007,  0.02784424, ..., -0.2273251 ,
         0.05086242,  0.00356852],
       [-0.14933634,  0.00746258,  0.05643443, ..., -0.06167357,
         0.06151193, -0.1357983 ],
       ...,
       [-0.00342201, -0.04674307,  0.07098466, ..., -0.21198863,
         0.05005572, -0.04259744],
       [-0.07456084,  0.05874615,  0.02859774, ..., -0.1783443 ,
         0.02612625, -0.03438443],
       [-0.04117168,  0.10616526,  0.00435033, ..., -0.16586548,
         0.0571876 , -0.05381043]], dtype=float32)

In [41]:
model.wv.get_normed_vectors().shape

(7432, 100)

In [42]:
y = model.wv.index_to_key

In [43]:
len(y)

7432

In [44]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'her',
 'you',
 'in',
 'it',
 'she',
 'had',
 'as',
 'him',
 'with',
 'that',
 'said',
 'not',
 'for',
 'at',
 'on',
 'they',
 'but',
 'is',
 'my',
 'lord',
 'no',
 'from',
 'them',
 'have',
 'would',
 'were',
 'be',
 'all',
 'your',
 'when',
 'ser',
 'me',
 'if',
 'will',
 'so',
 'jon',
 'could',
 'what',
 'one',
 'ned',
 'man',
 'their',
 'there',
 'king',
 'up',
 'out',
 'are',
 'this',
 'back',
 'been',
 'we',
 'do',
 'did',
 'father',
 'down',
 'tyrion',
 'like',
 'men',
 'by',
 'hand',
 'page',
 'eyes',
 'bran',
 'than',
 'now',
 'only',
 'or',
 'told',
 'see',
 'catelyn',
 'who',
 'more',
 'arya',
 'off',
 'here',
 'even',
 'an',
 'face',
 'boy',
 'over',
 'brother',
 'into',
 'know',
 'sansa',
 'old',
 'dany',
 'black',
 'robb',
 'before',
 'never',
 'looked',
 'robert',
 'well',
 'long',
 'time',
 'stark',
 'then',
 'yet',
 'head',
 'can',
 'too',
 'away',
 'made',
 'where',
 'night',
 'lady',
 'through',
 'lannister',
 'ma

In [45]:
3 # to reduce the dimension
from sklearn.decomposition import PCA

In [46]:
# plotting in 3-dimensions
pca = PCA(n_components=3)

In [47]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [48]:
X

array([[-0.3513859 , -0.20618129,  0.33773953],
       [-0.45339036, -0.049501  ,  0.22015283],
       [ 0.4394579 , -0.09880823,  0.0207908 ],
       ...,
       [ 0.00062823, -0.16962981, -0.3138424 ],
       [-0.19648497,  0.07890469,  0.03851208],
       [-0.16930105,  0.02703291, -0.01203659]], dtype=float32)

# Reduced dimensions from 100 to 3

In [49]:
X.shape

(7432, 3)

In [50]:
# plotting the 3-d data
import plotly.express as px

# Create an enhanced 3D scatter plot
fig = px.scatter_3d(
    X,
    x=0,
    y=1,
    z=2,
    color=y,  # Color points based on y values
    opacity=0.8,  # Make points slightly transparent for better visibility
    size_max=10,  # Adjust maximum point size
    title="Enhanced 3D Scatter Plot",
    labels={0: "X-axis", 1: "Y-axis", 2: "Z-axis"},  # Custom axis labels
)


fig.show()
